### ISSUE TITLE
Script not working , giving error 

### ISSUE THREAD

**Issue by Harry-kp** [Harry-kp/cheggbot#2]
INFO:root:Reading config.yaml file successfully..............
INFO:root:Fetching the ques..............
Traceback (most recent call last):
  File "script.py", line 29, in <module>
    bot.fetch_question()
  File "C:\Users\ROUNAK\Documents\cheggbot\chegg.py", line 102, in fetch_question
    res_data = json.loads(response.text)
  File "C:\Users\ROUNAK\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ROUNAK\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ROUNAK\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Harry-kp** [comment]
This issue has been fixed in the [PR](https://github.com/Harry-kp/cheggbot/pull/1).
